# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.29.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.29.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lucas/Documents/Pookie

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lucas/Documents/Pookie

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.29.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.29.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lucas/Documents/Pookie/CMakeFiles /Users/lucas/Documents/Pookie//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lucas/Documents/Pookie/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Pookie

# Build rule for target.
Pookie: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pookie
.PHONY : Pookie

# fast build rule for target.
Pookie/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pookie.dir/build.make CMakeFiles/Pookie.dir/build
.PHONY : Pookie/fast

src/__main.o: src/__main.c.o
.PHONY : src/__main.o

# target to build an object file
src/__main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pookie.dir/build.make CMakeFiles/Pookie.dir/src/__main.c.o
.PHONY : src/__main.c.o

src/__main.i: src/__main.c.i
.PHONY : src/__main.i

# target to preprocess a source file
src/__main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pookie.dir/build.make CMakeFiles/Pookie.dir/src/__main.c.i
.PHONY : src/__main.c.i

src/__main.s: src/__main.c.s
.PHONY : src/__main.s

# target to generate assembly for a file
src/__main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pookie.dir/build.make CMakeFiles/Pookie.dir/src/__main.c.s
.PHONY : src/__main.c.s

src/data.o: src/data.c.o
.PHONY : src/data.o

# target to build an object file
src/data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pookie.dir/build.make CMakeFiles/Pookie.dir/src/data.c.o
.PHONY : src/data.c.o

src/data.i: src/data.c.i
.PHONY : src/data.i

# target to preprocess a source file
src/data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pookie.dir/build.make CMakeFiles/Pookie.dir/src/data.c.i
.PHONY : src/data.c.i

src/data.s: src/data.c.s
.PHONY : src/data.s

# target to generate assembly for a file
src/data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pookie.dir/build.make CMakeFiles/Pookie.dir/src/data.c.s
.PHONY : src/data.c.s

src/fcrypt.o: src/fcrypt.c.o
.PHONY : src/fcrypt.o

# target to build an object file
src/fcrypt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pookie.dir/build.make CMakeFiles/Pookie.dir/src/fcrypt.c.o
.PHONY : src/fcrypt.c.o

src/fcrypt.i: src/fcrypt.c.i
.PHONY : src/fcrypt.i

# target to preprocess a source file
src/fcrypt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pookie.dir/build.make CMakeFiles/Pookie.dir/src/fcrypt.c.i
.PHONY : src/fcrypt.c.i

src/fcrypt.s: src/fcrypt.c.s
.PHONY : src/fcrypt.s

# target to generate assembly for a file
src/fcrypt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pookie.dir/build.make CMakeFiles/Pookie.dir/src/fcrypt.c.s
.PHONY : src/fcrypt.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Pookie"
	@echo "... src/__main.o"
	@echo "... src/__main.i"
	@echo "... src/__main.s"
	@echo "... src/data.o"
	@echo "... src/data.i"
	@echo "... src/data.s"
	@echo "... src/fcrypt.o"
	@echo "... src/fcrypt.i"
	@echo "... src/fcrypt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

